'use strict';
let _ = require('underscore');

let exp = {

  MSG_SUCCESS: 0,

  MSG_RESULT_UNKNOWN_ERROR: 1,
  MSG_RESULT_PARAM_ERROR: 2,
  MSG_RESULT_DB_ERROR: 3,
  MSG_RESULT_NO_SERVER: 4,
  MSG_RESULT_CACHE_ERROR: 5,
  MSG_RESULT_INVALID_URL: 6,
  MSG_RESULT_INVALID_VERSION: 7,
  MSG_RESULT_UNKNOWN_ROUTE: 8,
  MSG_RESULT_INVALID_USER_ID: 9,
  MSG_RESULT_REDIS_ERROR: 10,
  MSG_RESULT_SERVER_ID_REPEAT: 11,
  MSG_RESULT_NO_SUCH_SERVER_ID: 12,
  MSG_RESULT_UNIMPLEMENTED: 13, //未实现的功能
  MSG_RESULT_SERVER_MAINTAIN: 14, //服务器维护中 
  MSG_RESULT_SERVICE_UNREATCHABLE: 15, //暂时无法访问服务
  MSG_RESULT_DATA_ERROR: 16,

  MSG_RESULT_INVALID_USERNAME: 101,
  MSG_RESULT_INVALID_PASSWORD: 102,

}
let CodeMsg = _(exp).invert();
exp.msg = function(code) {
  return CodeMsg[code];
};

module.exports = exp;